### ISSUE TITLE
Use isomorphic-ws

### ISSUE THREAD

**Issue by paralin** [alanshaw/it-ws#20]
To make this compatible with the web browser, use isomorphic-ws instead of ws.

**Comment by achingbrain** [comment]
This module runs it's tests in CI in the browser without issue, and `isomorphic-ws` uses [similar mechanisms](https://github.com/heineiuo/isomorphic-ws/blob/master/package.json#L7) to [this module](https://github.com/alanshaw/it-ws/blob/master/package.json#L194-L196) to load `ws` for node only so this may be down to your project config.

Can you please share a minimal repro case?

**Comment by paralin** [comment]
@achingbrain I can have a look at making a repro, but I'm running into this again-

importing it-ws imports "events" which isn't available on the browser side:

```
✘ [ERROR] Could not resolve "events"

    ../../../../node_modules/it-ws/dist/src/server.js:5:29:
      5 │ import { EventEmitter } from 'events';
        ╵                              ~~~~~~~~

  The package "events" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "Platform: api.PlatformNode" to do that, which will remove this
  error.
```

**Comment by paralin** [comment]
Reproduction: https://github.com/paralin/it-ws-issue-20/blob/master/package.json#L7
