### ISSUE TITLE
Export WebSocket

### ISSUE THREAD

**Issue by paralin** [alanshaw/it-ws#78]
import WebSocket from 'it-ws/dist/src/web-socket.js';

Would it be possible to add an export for `import WebSocket from 'it-ws/websocket'` ?

Thanks.

**Comment by paralin** [comment]
@achingbrain Hi - still need this, I've been using this hack:

```
import WebSocket from 'it-ws/dist/src/web-socket.js'
```

But that doesn't work anymore as it's not in exports.

**Comment by achingbrain** [comment]
It’s worth noting that node 21 [will have a websocket implementation](https://www.infoworld.com/article/3709068/nodejs-21-brings-websocket-client.amp.html) so you should probably switch to that when it’s no longer behind a flag.

**Comment by paralin** [comment]
@achingbrain thanks. Does that also work in the web browser? I guess it would since the type is available in both places natively.

**Comment by achingbrain** [comment]
Yes, it’ll be global in both environments.
